resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: registry.cn-shenzhen.aliyuncs.com/dll_samdeng/mysql-operator
  newTag: v0.2.0
